### ISSUE TITLE
Request: can do a NVWebDriver Led fix

### ISSUE THREAD

**Issue by oscarbg** [mologie/NVWebDriverLibValFix#2]
Hi,
this is not a issue per se but a request..
people with light/LED enabled cards have support from Nvidia (via utils) for disabling completely the light on both Windows and Linux (Win is via nvled tool Linux via command line arguments to his nvidia settings if remember correctly)..
lacking is Macos support to disable the default on light or do other things..
since you seem to be able to patch Nvidia driver with your kext can see if posible to patch driver to disable light..
last time I searched Macos driver binaries I found references to LED functions.. can post some more info if wanted..
thanks..

**Comment by mologie** [comment]
> since you seem to be able to patch Nvidia driver with your kext can see if posible to patch driver to disable light..

Sorry, I don't plan to look into this, but I'll be available to assist if you figure out how to implement it exactly and need pointers on how to work on it on kernel level. Though I doubt a kernel patch is needed at all - most likely, you'll be able to control the LEDs from user mode via IOKit *if* NVIDIA's drivers really implement the functionality.
