### ISSUE TITLE
Nvidia Fix

### ISSUE THREAD

**Issue by daslicht** [mologie/NVWebDriverLibValFix#4]
May this fix also work for such kind of errors, please?

https://gist.github.com/daslicht/0d847690aa4dd78d013c1a26f9a6f107

**Comment by mologie** [comment]
In your crash log, the NVIDIA driver was loaded successfully (which is what this driver is for):

```
0x113c3c000 -        0x113f9afff  com.nvidia.web.GeForceMTLDriverWeb (10.17.34 - 10.1.7) <896229F0-9C96-39FA-AB80-0BFC4FB3D8EF> /System/Library/Extensions/GeForceMTLDriverWeb.bundle/Contents/MacOS/GeForceMTLDriverWeb
```

Thus, this patch of mine is unlikely to make a difference for your crash issue. The crash log looks like a regular error in the app that crashed - please contact its developer.

**Comment by efluon** [comment]
actually it looks like an error in the loaded plugin, not in maschine. and if you look at what the plugin looks like, and where it crashes (view/modulation) i’d wager it is a problem with openGL.. those devs should know about it..

**Comment by daslicht** [comment]
Thank you very much for this insight!
