### ISSUE TITLE
Issue with installing?

### ISSUE THREAD

**Issue by xenmaster47** [mologie/NVWebDriverLibValFix#7]
Hey I have been battling the GameScene.sks crashing my hackintosh today. When trying to install via terminal this is what I get:

Admins-Mac:~ admin$ sudo tar -xv -C /Library/Extensions -f ~/Downloads/NVWebDriverLibValFix.kext.1.0.0.tar.gz
Password:
tar: Error opening archive: Failed to open '/Users/admin/Downloads/NVWebDriverLibValFix.kext.1.0.0.tar.gz'
Admins-Mac:~ admin$ sudo kextutil /Library/Extensions/NVWebDriverLibValFix.kext
Cache file /System/Library/Caches/com.apple.kext.caches/Directories/Library/Extensions/KextIdentifiers.plist.gz is out of date; not using.
Diagnostics for NVWebDriverLibValFix.kext:
Authentication Failures: 
    File owner/permissions are incorrect (must be root:wheel, nonwritable by group/other): 
        NVWebDriverLibValFix.kext
        Contents
        Info.plist
        MacOS
        NVWebDriverLibValFix

Code Signing Failure: not code signed

I disabled kernel code signing, is there anything else I need to do?

Any help would be appreciated.

**Comment by mologie** [comment]
The permission issues suggest that you tried to manually move the kext to /Library/Extensions before. If that is the case, delete it from /Library/Extensions with Finder or via `sudo rm -rf /Library/Extensions/NVWebDriverLibValFix.kext`.

Let's address the 'file not found error of the first command next'. The command from the releases page only works when the .tar.gz file that you download is indeed in your user's Downloads folder. Adjust the path in the command or move the tar.gz file there first, then try again.

**Comment by xenmaster47** [comment]
Admins-Mac:~ admin$ sudo tar -xv -C /Library/Extensions -f ~/Downloads/NVWebDriverLibValFix.kext.1.0.0.tar.gz
Password:
tar: Error opening archive: Failed to open '/Users/admin/Downloads/NVWebDriverLibValFix.kext.1.0.0.tar.gz'
Admins-Mac:~ admin$ 

So I removed the files from my /Library/Extensions and also cleared my downloads folder before re downloading. 

I can manually open the tar file if that works still?

**Comment by mologie** [comment]
I've played around with the browser settings a bit. Are you by chance using Safari for downloading the .tar.gz file? Safari seems to extract the .tar.gz partially, resulting in a .tar file. We really don't want that for the installation process.

Go to the downloads page again, *right click* on the .tar.gz link, select 'Download Linked File As...' and finally select your 'Downloads' folder. Then, repeat entering the commands from the releases page.

I'll add a hint for Safari users to the downloads page.

**Comment by xenmaster47** [comment]
I'll report back if it works later, but definitely was able to make progress, this is my terminal now: (but like I said, haven't checked with Xcode if it definitively worked. Thanks for all the help so far!)

Admins-Mac:~ admin$ sudo tar -xv -C /Library/Extensions -f ~/Downloads/NVWebDriverLibValFix.kext.1.0.0.tar.gz
Password:
x NVWebDriverLibValFix.kext/
x NVWebDriverLibValFix.kext/Contents/
x NVWebDriverLibValFix.kext/Contents/Info.plist
x NVWebDriverLibValFix.kext/Contents/MacOS/
x NVWebDriverLibValFix.kext/Contents/MacOS/NVWebDriverLibValFix
Admins-Mac:~ admin$ sudo kextutil /Library/Extensions/NVWebDriverLibValFix.kext
Diagnostics for /Library/Extensions/NVWebDriverLibValFix.kext:
Code Signing Failure: not code signed
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext "/Library/Extensions/NVWebDriverLibValFix.kext"
kext signature failure override allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext "/Library/Extensions/NVWebDriverLibValFix.kext"
