### ISSUE TITLE
Will this work on Monterey 12.3.1

### ISSUE THREAD

**Issue by AK-3696** [mologie/NVWebDriverLibValFix#9]
I have a hackintosh with opencore Monterey 12.3.1 also using whatevergreen.kext and Nvidia kepler patcher. Will this work on my machine? I cannot open simulator on xcode. It is just a black screen

**Comment by mologie** [comment]
Nope, this will not fix your problem, sorry. This extension is obsolete, WhateverGreen replaces it.
